DROP DATABASE IF EXISTS ADDRESS_BOOK_DEV;
DROP DATABASE IF EXISTS ADDRESS_BOOK_TEST;

CREATE DATABASE ADDRESS_BOOK_DEV;
CREATE DATABASE ADDRESS_BOOK_TEST;

CREATE USER IF NOT EXISTS 'address_book'@'localhost' IDENTIFIED BY '';

GRANT ALL PRIVILEGES ON ADDRESS_BOOK_DEV.* TO 'address_book' @'localhost';
GRANT ALL PRIVILEGES ON ADDRESS_BOOK_TEST.* TO 'address_book' @'localhost';