CREATE TABLE ACCOMMODATION
(
  ID                 BIGINT(20) NOT NULL AUTO_INCREMENT,
  ADDRESS_ID         BIGINT(20),
  PERSON_ID          BIGINT(20),
  ACCOMMODATION_DATE DATE,
  SINGLE_OWNED       BIT(1),

  PRIMARY KEY (ID)
)
  ENGINE = innodb
  DEFAULT CHARSET = utf8;